### ISSUE TITLE
能否提供数据集下载地址和数据集处理代码，谢谢。

### ISSUE THREAD

**Issue by qingyi3** [BokwaiHo/DEGC#1]

**Comment by BokwaiHo** [comment]
Hi, thanks for your interest to our project. 
The dataset link:  
   Taobao2014: https://tianchi.aliyun.com/dataset/dataDetail?dataId=46
   Taobao2015: https://tianchi.aliyun.com/dataset/dataDetail?dataId=53
   Netflix: https://academictorrents.com/details/9b13183dc4d60676b773c9e2cd6de5e5542cee9a
   Foursquare: https://sites.google.com/site/yangdingqi/home/foursquare-dataset

As for the dataset preprocessing code, maybe you can refer to this file: 
    https://github.com/BokwaiHo/DEGC/blob/main/data_utils/full_preprosess_dataset.ipynb.

For more details, please read and cite our paper:  https://arxiv.org/abs/2303.11700
